# The `meta` group contains top level attributes that govern the
# behaviour of the MPM Solver.
#
# Attributes:
# title:    The title of the experiment. This is just for the user's
#           reference.
# type:     The type of simulation to be used. Allowed values are
#           {"MPMExplicit"}
# scheme:   The MPM Scheme used for simulation. Allowed values are
#           {"usl", "usf"}
# dt:       Timestep used in the simulation.
# nsteps:   Number of steps to run the simulation for.
[meta]
title = "Example TOML Input for 2D MPM"
type = "MPMExplicit"
dimension = 2
scheme = "usf"
dt = 0.01
nsteps = 1000
velocity_update = true

[output]
format = "npz"
folder = "results/"
step_frequency = 5

[mesh]
# type = "file"
# file = "mesh-1d.txt"
# boundary_nodes = "boundary-1d.txt"
# particle_element_ids = "particles-elements.txt"
type = "generator"
nelements = [3, 1]
element_length = [0.1, 0.1]
particle_element_ids = [0]
element = "Quadrilateral4Node"

[[mesh.constraints]]
node_ids = [0, 1]
dir = 1
velocity = 0.0

[[mesh.constraints]]
node_ids = [2, 3]
dir = 1
velocity = 0.1

[[materials]]
id = 0
density = 1
poisson_ratio = 1
youngs_modulus = 100
type = "LinearElastic"

[[particles]]
file = "examples/particles-2d-nodal-force.json"
material_id = 0
init_velocity = 0.1

[external_loading]
gravity = [0, 0]

[[external_loading.concentrated_nodal_forces]]
node_ids = [0, 1]
math_function_id = 0
dir = 1
force = 10.5

[[external_loading.particle_surface_traction]]
pset = [0]
pids = [1, 3]
dir = 1
math_function_id = 0
traction = 10

[[math_functions]]
type = "Linear"
xvalues = [0.0, 0.5, 1.0]
fxvalues = [1.0, 1.0, 1.0]
