# The `meta` group contains top level attributes that govern the
# behaviour of the MPM Solver.
#
# Attributes:
# title:    The title of the experiment. This is just for the user's
#           reference.
# type:     The type of simulation to be used. Allowed values are
#           {"MPMExplicit"}
# scheme:   The MPM Scheme used for simulation. Allowed values are
#           {"usl", "usf"}
# dt:       Timestep used in the simulation.
# nsteps:   Number of steps to run the simulation for.
[meta]
title = "uniaxial-stress-usf"
type = "MPMExplicit"
dimension = 2
scheme = "usf"
dt = 0.01
nsteps = 10
velocity_update = false

[output]
format = "npz"
folder = "results/"
step_frequency = 1

[mesh]
type = "generator"
nelements = [1, 1]
element_length = [1, 1]
particle_element_ids = [0]
element = "Quadrilateral4Node"
entity_sets = "entity_sets.json"

[[mesh.constraints]]
nset_ids = [0]
dir = 1
velocity = 0.0

[[mesh.constraints]]
nset_ids = [1]
dir = 1
velocity = -0.01

[[materials]]
id = 0
density = 1
poisson_ratio = 0
youngs_modulus = 1000
type = "LinearElastic"

[[particles]]
file = "particles-2d-uniaxial-stress.json"
material_id = 0
init_velocity = [1.0, 0.0]

[external_loading]
gravity = [0, 0]
